"""Actual medical form regression with fictional data and isolated localhost Vite."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
from playwright.sync_api import sync_playwright, expect

parser = argparse.ArgumentParser()
parser.add_argument('--output')
args = parser.parse_args()
repo = Path(__file__).resolve().parents[2]
output = Path(args.output) if args.output else Path(tempfile.mkdtemp(prefix='fafee-medical-ui-'))
output.mkdir(parents=True, exist_ok=True)
checks, errors, api_requests, external_requests, http_failures = [], [], [], [], []


def check(name, condition=True):
    if not condition:
        raise AssertionError(name)
    checks.append(name)


def fill(page, name, value):
    locator = page.locator(f'[name="{name}"]')
    if not locator.is_visible():
        details = page.locator('.mp-supplementary')
        if details.get_attribute('open') is None:
            details.locator(':scope > summary').click()
    locator.fill(value)


def reset(page):
    page.get_by_role('button', name='新建测算', exact=True).click()
    dialog = page.get_by_role('dialog')
    if dialog.is_visible():
        dialog.get_by_role('button', name='清空条件', exact=True).click()


def national(page):
    page.locator('[name="region"]').select_option('national')
    for name, value in {'hireDate':'2025-11-02','totalWorkYears':'1','segments.0.startDate':'2026-02-02','segments.0.endDate':'2026-02-06'}.items():
        fill(page,name,value)
    page.locator('[name="historyComplete"]').check()


def shanghai(page):
    page.locator('[name="region"]').select_option('shanghai')
    page.get_by_role('button',name='填写实际日期段',exact=True).click()
    for name,value in {'hireDate':'2024-09-01','asOf':'2026-06-30','segments.0.startDate':'2026-06-01','segments.0.endDate':'2026-06-10','segments.0.workDays':'8'}.items():
        fill(page,name,value)
    page.locator('[name="historyComplete"]').check()


server = subprocess.Popen(['node',str(repo/'server/scripts/serve-medical-period-review.js')],cwd=repo,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,encoding='utf-8',creationflags=getattr(subprocess,'CREATE_NO_WINDOW',0))
try:
    url, review_root = None, None
    for line in server.stdout:
        if line.strip().startswith('{'):
            ready = json.loads(line)
            if ready.get('type') == 'medical-review-ready':
                url, review_root = ready['url'],Path(ready['root'])
                break
    if not url:
        raise RuntimeError('Isolated review server did not start.')
    with sync_playwright() as p:
        browser=p.chromium.launch(executable_path=os.environ.get('MEDICAL_TEST_BROWSER',r'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'),headless=True)
        context=browser.new_context(viewport={'width':1440,'height':1000},reduced_motion='reduce')
        context.add_init_script("""(() => {
          Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__medicalCopied=text}}});
          const get=Storage.prototype.getItem,set=Storage.prototype.setItem,remove=Storage.prototype.removeItem;
          const seeds={
            'fafee-history-v2:fictional-medical-review-user:medical-calculator:calculations':'{"version":2,"records":[{"id":"old","input":{"region":"shanghai"},"result":{"algorithmVersion":"old"}}]}',
            'fafee-history-v2:another-user:medical-calculator:calculations':'corrupt-old-history',
            'pension-unrelated-test':'untouched'
          };
          for(const [key,value] of Object.entries(seeds)) if(get.call(localStorage,key)===null) set.call(localStorage,key,value);
          window.__medicalStorageCalls=[];
          for(const [name,original] of [['getItem',get],['setItem',set],['removeItem',remove]]) Storage.prototype[name]=function(key,...args){if(String(key).includes('medical-calculator'))window.__medicalStorageCalls.push([name,key]);return original.call(this,key,...args)};
          window.__medicalStorageUnchanged=()=>Object.entries(seeds).every(([key,value])=>get.call(localStorage,key)===value);
        })()""")
        page=context.new_page()
        page.on('pageerror',lambda error:errors.append(str(error)))
        page.on('console',lambda message:errors.append(message.text) if message.type=='error' else None)
        page.on('request',lambda request:external_requests.append(request.url) if request.url.startswith(('http:','https:')) and not request.url.startswith(url) else None)
        page.on('request',lambda request:api_requests.append(request.url) if '/api/' in request.url else None)
        page.on('response',lambda response:http_failures.append(f'{response.status} {response.url}') if response.status>=400 else None)

        def untouched(label):
            check(label,page.evaluate('window.__medicalStorageCalls.length===0 && window.__medicalStorageUnchanged()'))

        def submit():
            page.locator('button[type="submit"]').last.click()
            expect(page.locator('.mp-result')).to_be_visible()

        def receipt():
            page.get_by_role('button',name='复制测算单',exact=True).click()
            expect(page.locator('.mp-notice')).to_contain_text('已复制')
            text=page.evaluate('window.__medicalCopied')
            check('receipt has no decimal months or calculation process',not re.search(r'\d+\.\d+\s*个月',text) and '计算过程' not in text)
            return text

        page.goto(url,wait_until='networkidle')
        check('empty form ignores old snapshots',page.locator('[name="region"]').input_value()=='' and page.locator('.mp-result').count()==0)
        check('no history sidebar, account panel or composer',page.locator('.chat-sidebar,.mp-history-list,.composer,.account-trigger,.sidebar-toggle').count()==0)
        check('enterprise title',page.get_by_role('heading',name='员工医疗期测算',exact=True).is_visible())
        check('form help closed by default',page.locator('.mp-form-guide').get_attribute('open') is None and page.locator('.mp-field > small:visible').count()==0)
        untouched('initial render never reads or modifies old history')
        page.screenshot(path=str(output/'desktop-empty.png'))
        page.get_by_role('button',name='开始测算',exact=True).click()
        expect(page.get_by_role('alert')).to_contain_text('输入已保留')
        check('missing input focuses region',page.locator('[name="region"]').evaluate('(e)=>e===document.activeElement'))
        reset(page)
        national(page)
        check('national form keeps four required inputs',page.locator('form .mp-field input:visible').count()==4)
        check('tenure baseline stated in field label','最早病休开始日' in page.locator('label[for="mp-totalWorkYears"]').inner_text())
        check('key tenure instructions are visible beside the field',page.locator('[name="totalWorkYears"] + span').count()==1 and page.locator('.mp-basic-fields .mp-field-hint').is_visible() and '以前单位工龄' in page.locator('.mp-basic-fields .mp-field-hint').inner_text())
        check('record mode belongs to records rather than remarks',page.locator('.mp-record-fields [role="group"][aria-label="病休记录方式"]').is_visible() and page.locator('.mp-supplementary .mp-choice').count()==0)
        check('inclusive date and gap instructions appear beside record type','未病休的间隔不计' in page.locator('.mp-record-type').inner_text())
        page.locator('.mp-supplementary > summary').click()
        fill(page,'specialNote','普通备注')
        spacing=page.evaluate("""() => {
          const remarks=document.querySelector('[name="specialNote"]').getBoundingClientRect();
          const exceptions=document.querySelector('.mp-exceptions').getBoundingClientRect();
          const label=document.querySelector('label[for="mp-specialNote"]').getBoundingClientRect();
          const choice=document.querySelector('.mp-record-mode .mp-choice');
          return {exceptionGap:label.top-exceptions.bottom,optionGap:parseFloat(getComputedStyle(choice).gap), separated:remarks.top>exceptions.bottom};
        }""")
        check('remarks and exception options have24px separation',spacing['exceptionGap']>=24 and spacing['optionGap']>=12 and spacing['separated'])
        page.locator('.mp-supplementary').screenshot(path=str(output/'desktop-supplement-spacing.png'))
        page.set_viewport_size({'width':320,'height':900})
        check('expanded supplementary form fits320px',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        page.locator('.mp-supplementary').screenshot(path=str(output/'mobile-supplement-spacing.png'))
        page.set_viewport_size({'width':1440,'height':1000})
        page.locator('.mp-supplementary > summary').click()
        page.screenshot(path=str(output/'desktop-continuous-form.png'))
        submit()
        check('continuous quota3,used5,remaining84calendarreference',all(v in page.locator('.mp-metrics').inner_text() for v in ['3','5','84','参考','天']))
        check('result has collapsed guide and no process',page.locator('.mp-result-guide').get_attribute('open') is None and page.locator('.mp-process').count()==0)
        check('page has no decimal months',not re.search(r'\d+\.\d+\s*个月',page.locator('.mp-result').text_content()))
        check('continuous copy matches visible84calendar days','84天' in receipt())
        check('page and copy have no fixed30day monthly conversion','30天/月' not in page.locator('.medical-calculator').text_content() and '30天/月' not in receipt())
        untouched('calculate and copy leave history intact')
        page.screenshot(path=str(output/'desktop-continuous-result.png'))
        page.get_by_role('button',name='修改条件',exact=True).click()
        fill(page,'segments.0.endDate','2026-02-07')
        check('modified input disables stale copy',page.locator('.mp-result-stale').count()==1 and page.get_by_role('button',name='复制测算单',exact=True).is_disabled())
        submit()
        check('recalculation gives83 and clears stale state','83' in page.locator('.mp-balance').inner_text() and page.locator('.mp-result-stale').count()==0)
        page.get_by_role('button',name='修改条件',exact=True).click()
        fill(page,'segments.0.endDate','2026-02-01')
        page.get_by_role('button',name='重新计算',exact=True).click()
        expect(page.get_by_role('alert')).to_be_visible()
        check('reversed dates retain inputs and disable copy',page.locator('[name="segments.0.endDate"]').input_value()=='2026-02-01' and page.get_by_role('button',name='复制测算单',exact=True).is_disabled())
        reset(page)
        untouched('reset and recalculation leave old history untouched')
        national(page)
        fill(page,'totalWorkYears','9')
        check('ten-year date promoted beside tenure only when needed',page.locator('.mp-basic-fields [name="tenYearDate"]').is_visible() and '核对余额需要' in page.locator('label[for="mp-tenYearDate"]').inner_text())
        submit()
        check('missing10year date has specific reason and preserves count','请补充累计工龄满10年日期' in page.locator('.mp-balance').inner_text() and '5' in page.locator('.mp-metrics').inner_text())
        check('unknown balance is not zero',page.locator('.mp-balance strong').inner_text()=='待核对')
        page.get_by_role('button',name='补充信息',exact=True).click()
        expect(page.locator('[name="tenYearDate"]')).to_be_focused()
        check('balance supplement targets the ten-year date')
        page.screenshot(path=str(output/'desktop-ten-year-supplement.png'))
        page.set_viewport_size({'width':320,'height':900})
        check('promoted ten-year field fits320px',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        page.locator('[name="tenYearDate"]').scroll_into_view_if_needed()
        page.screenshot(path=str(output/'mobile-ten-year-supplement.png'))
        page.set_viewport_size({'width':1440,'height':1000})
        fill(page,'tenYearDate','2026-12-01')
        check('provided ten-year date stays beside tenure',page.locator('.mp-basic-fields [name="tenYearDate"]').is_visible())
        submit()
        check('providing future threshold restores calendar84days','84' in page.locator('.mp-balance').inner_text())
        page.get_by_role('button',name='修改条件',exact=True).click()
        fill(page,'tenYearDate','2020-01-01')
        page.get_by_role('button',name='重新计算',exact=True).click()
        expect(page.get_by_role('alert')).to_contain_text('矛盾')
        check('contradictory tenure blocks recalculation')
        reset(page)
        national(page)
        fill(page,'hireDate','2022-01-01')
        fill(page,'totalWorkYears','4')
        page.get_by_role('button',name='非连续分段',exact=True).click()
        for i,start,end in [(0,'2023-04-04','2023-04-08'),(1,'2024-06-06','2024-06-13'),(2,'2025-09-09','2025-09-17')]:
            if i:page.get_by_role('button',name='添加一段病休',exact=True).click()
            fill(page,f'segments.{i}.startDate',start)
            fill(page,f'segments.{i}.endDate',end)
        check('continuous switch cannot silently discard segments',page.get_by_role('button',name='连续病休',exact=True).is_disabled())
        contrast=page.evaluate(r"""() => {
          const lum=c=>c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
          return [...document.querySelectorAll('.mp-field > label,.mp-choice-secondary button[aria-pressed="true"]')].filter(e=>e.offsetParent).map(e=>{let parent=e,bg='rgb(255,255,255)';while(parent){const c=getComputedStyle(parent).backgroundColor;if(c!=='rgba(0, 0, 0, 0)'&&c!=='transparent'){bg=c;break;}parent=parent.parentElement;}const a=lum(getComputedStyle(e).color),b=lum(bg);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)})
        }""")
        check('labels and selected buttons meet4.5contrast',contrast and min(contrast)>=4.5)
        page.screenshot(path=str(output/'desktop-segmented-form.png'))
        submit()
        expect(page.locator('.mp-segment-result')).to_have_count(3)
        check('total22days and three separate reference periods','22' in page.locator('.mp-metrics').inner_text() and page.locator('.mp-period-badge').all_text_contents()==['参考周期 1','参考周期 2','参考周期 3'])
        for i,days,boundary,balance in [(0,5,'2023-10-04',86),(1,8,'2024-12-06',84),(2,9,'2026-03-09',82)]:
            card=page.locator('.mp-segment-result').nth(i)
            check(f'segment{i+1} displays dates,usage,balance',f'{days}自然日' in card.inner_text() and boundary in card.inner_text() and f'{balance}天（参考）' in card.inner_text())
        check('segment copied calendar days match all cards',all(f'{v}天（参考）' in receipt() for v in [86,84,82]))
        check('each segment reveals its calendar budget',all(f'{v}个实际日历天' in page.locator('.mp-segment-result').nth(i).inner_text() for i,v in enumerate([91,92,91])))
        page.locator('.mp-segment-results').screenshot(path=str(output/'desktop-segmented-cards.png'))
        for width in [1440,1024,768,390,320]:
            page.set_viewport_size({'width':width,'height':900})
            check(f'result no overflow at{width}',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
            check(f'no sidebar at{width}',page.locator('.chat-sidebar').count()==0)
        page.screenshot(path=str(output/'mobile-segmented-result.png'))
        page.get_by_role('button',name='修改条件',exact=True).click()
        for width in [390,320]:
            page.set_viewport_size({'width':width,'height':900})
            check(f'form no overflow at{width}',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        page.screenshot(path=str(output/'mobile-form.png'))
        page.set_viewport_size({'width':1440,'height':1000})
        page.locator('[name="historyComplete"]').uncheck()
        submit()
        check('incomplete history blocks each balance,retains all cards',page.locator('.mp-segment-pending').count()==3 and '补齐' in page.locator('.mp-balance').inner_text())
        check('unconfirmed national history is labeled recorded only','已录入病休' in page.locator('.mp-metrics').inner_text())
        page.get_by_role('button',name='补充信息',exact=True).click()
        expect(page.locator('[name="historyComplete"]')).to_be_focused()
        check('national supplement focuses completeness confirmation')
        untouched('segmented operations do not touch saved history')
        reset(page)
        national(page)
        page.get_by_role('button',name='非连续分段',exact=True).click()
        for i,start,end in [(0,'2026-02-02','2026-02-06'),(1,'2026-03-02','2026-03-09'),(2,'2026-04-06','2026-04-10')]:
            if i:page.get_by_role('button',name='添加一段病休',exact=True).click()
            fill(page,f'segments.{i}.startDate',start)
            fill(page,f'segments.{i}.endDate',end)
        submit()
        check('same cycle accumulates5,13,18',all(f'{v}自然日' in page.locator('.mp-segment-result').nth(i).inner_text() for i,v in enumerate([5,13,18])))
        check('same calendar budget balances84,76,71',all(f'{v}天（参考）' in page.locator('.mp-segment-result').nth(i).inner_text() for i,v in enumerate([84,76,71])))
        page.get_by_role('button',name='修改条件',exact=True).click()
        fill(page,'segments.1.startDate','2026-02-04')
        page.get_by_role('button',name='重新计算',exact=True).click()
        expect(page.get_by_role('alert')).to_be_visible()
        check('overlap blocks calculation')
        reset(page)
        national(page)
        page.locator('.mp-supplementary > summary').click()
        page.get_by_role('button',name='只有首日与累计量',exact=True).click()
        fill(page,'asOf','2026-03-31')
        fill(page,'summary.firstDate','2026-02-02')
        fill(page,'summary.naturalDays','23')
        submit()
        check('summary23retained without inventing dates or balances','23' in page.locator('.mp-metrics').inner_text() and '实际病休日期段' in page.locator('.mp-balance').inner_text() and page.locator('.mp-segment-result').count()==0)
        page.get_by_role('button',name='修改条件',exact=True).click()
        page.get_by_role('button',name='有实际日期段',exact=True).click()
        check('recordmode switch preserves date draft',page.locator('[name="segments.0.endDate"]').input_value()=='2026-02-06')
        reset(page)
        shanghai(page)
        check('Shanghai hides national fields',page.locator('[name="totalWorkYears"],[name="tenYearDate"]').count()==0)
        submit()
        check('Shanghai remaining54.01workdays',page.locator('.mp-balance strong').inner_text()=='54.01工作日')
        check('Shanghai copy is in workdays','54.01工作日' in receipt())
        page.get_by_role('button',name='修改条件',exact=True).click()
        page.get_by_role('button',name='非连续分段',exact=True).click()
        page.get_by_role('button',name='添加一段病休',exact=True).click()
        for name,value in {'segments.1.startDate':'2026-06-15','segments.1.endDate':'2026-06-20','segments.1.workDays':'5'}.items():fill(page,name,value)
        submit()
        check('Shanghai13used,49.01remaining',page.locator('.mp-balance strong').inner_text()=='49.01工作日' and '13' in page.locator('.mp-metrics').inner_text())
        check('Shanghai segmentation does not reset quota','54.01工作日' in page.locator('.mp-segment-result').nth(0).inner_text() and '49.01工作日' in page.locator('.mp-segment-result').nth(1).inner_text())
        check('Shanghai49.01copy matches page','49.01工作日' in receipt())
        page.screenshot(path=str(output/'desktop-shanghai-result.png'))
        reset(page)
        shanghai(page)
        fill(page,'segments.0.workDays','')
        check('Shanghai has one measurement action',page.get_by_role('button',name='仅核对基础额度',exact=True).count()==0 and page.locator('button[type="submit"]').count()==1)
        submit()
        check('missing workdays retain quota and give specific reason','未提供' in page.locator('.mp-metrics').inner_text() and '补充实际病休工作日' in page.locator('.mp-balance').inner_text() and page.get_by_role('alert').count()==0)
        check('known dates retain natural-day statistic when workdays unknown','10自然日' in page.locator('.mp-metrics').inner_text())
        page.get_by_role('button',name='补充信息',exact=True).click()
        expect(page.locator('[name="segments.0.workDays"]')).to_be_focused()
        check('Shanghai supplement focuses missing segment workdays')
        fill(page,'segments.0.workDays','8')
        page.locator('[name="historyComplete"]').uncheck()
        submit()
        check('unconfirmed Shanghai history preserves recorded8 without balance','8' in page.locator('.mp-metrics').inner_text() and '已录入病休' in page.locator('.mp-metrics').inner_text() and '补齐' in page.locator('.mp-balance').inner_text())
        page.get_by_role('button',name='补充信息',exact=True).click()
        expect(page.locator('[name="historyComplete"]')).to_be_focused()
        page.locator('[name="historyComplete"]').check()
        page.get_by_role('button',name='非连续分段',exact=True).click()
        page.get_by_role('button',name='添加一段病休',exact=True).click()
        fill(page,'segments.1.startDate','2026-06-15')
        fill(page,'segments.1.endDate','2026-06-20')
        submit()
        check('partial Shanghai workdays are counted without calling them complete','8工作日（部分）' in page.locator('.mp-metrics').inner_text() and '8工作日（部分）' in receipt() and page.locator('.mp-balance strong').inner_text()=='待核对')
        page.get_by_role('button',name='补充信息',exact=True).click()
        expect(page.locator('[name="segments.1.workDays"]')).to_be_focused()
        check('partial segment supplement targets the missing row')
        page.get_by_role('button',name='填写累计工作日',exact=True).click()
        check('Shanghai switch uses the cumulative workday label',page.locator('[name="summary.workDays"]').is_visible())
        reset(page)
        page.locator('[name="region"]').select_option('shanghai')
        check('Shanghai workday and date instructions are beside the fields',page.locator('.mp-record-fields .mp-field-hint').count()==2 and '不表示此后一直病休' in page.locator('.mp-record-fields').inner_text())
        check('Shanghai history defaults unconfirmed and supplement defaults closed',not page.locator('[name="historyComplete"]').is_checked() and page.locator('.mp-supplementary').get_attribute('open') is None)
        check('supplement summary no generic optional label','选填' not in page.locator('.mp-supplementary > summary').inner_text())
        check('Shanghai guide does not mix national tenure and cutoff instructions','累计工龄' not in page.locator('.mp-form-guide').text_content() and '默认取最晚' not in page.locator('.mp-form-guide').text_content() and '不表示期间连续病休' in page.locator('.mp-form-guide').text_content())
        fill(page,'hireDate','2024-09-01')
        fill(page,'asOf','2026-06-30')
        page.get_by_role('button',name='开始测算',exact=True).click()
        expect(page.get_by_role('alert')).to_contain_text('首次病休日期或实际累计病休工作日')
        check('Shanghai empty record requires a usable date or quantity')
        fill(page,'summary.workDays','0')
        page.locator('[name="historyComplete"]').check()
        submit()
        check('explicit zero is kept while missing first date prevents balance','0工作日' in page.locator('.mp-metrics').inner_text() and '首次病休日期' in page.locator('.mp-balance').inner_text())
        page.get_by_role('button',name='补充信息',exact=True).click()
        expect(page.locator('[name="summary.firstDate"]')).to_be_focused()
        check('summary supplement focuses missing first date')
        fill(page,'summary.firstDate','2026-03-01')
        fill(page,'summary.workDays','')
        submit()
        check('known summary date retains quota without inventing zero workdays','未提供' in page.locator('.mp-metrics').inner_text() and '补充实际病休工作日' in page.locator('.mp-balance').inner_text())
        page.set_viewport_size({'width':320,'height':900})
        check('partial result and supplement fit320px',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        page.screenshot(path=str(output/'mobile-shanghai-partial.png'))
        page.set_viewport_size({'width':1440,'height':1000})
        page.screenshot(path=str(output/'desktop-shanghai-partial.png'))
        reset(page)
        page.locator('[name="region"]').select_option('shanghai')
        for name,value in {'hireDate':'2024-09-01','asOf':'2026-06-30','summary.firstDate':'2026-03-01','summary.workDays':'62'}.items():fill(page,name,value)
        page.locator('[name="historyComplete"]').check()
        submit()
        check('tiny positive balance stays0.01workday',page.locator('.mp-balance strong').inner_text()=='0.01工作日')
        check('tiny positive receipt stays0.01workday','0.01工作日' in receipt())
        for value,expected in [('62.01','0工作日'),('0','62.01工作日')]:
            page.get_by_role('button',name='修改条件',exact=True).click()
            fill(page,'summary.workDays',value)
            submit()
            check(f'explicit workdays{value} accurate budget',page.locator('.mp-balance strong').inner_text()==expected)
        for region,fixture,balance in [('national',national,'84天'),('Shanghai',shanghai,'54.01工作日')]:
            reset(page)
            fixture(page)
            page.locator('.mp-supplementary > summary').click()
            page.locator('.mp-exceptions > summary').click()
            check(f'{region} exceptions use clear section name','特殊情况与延长约定' in page.locator('.mp-exceptions > summary').inner_text())
            fill(page,'specialNote','普通备注：资料复核，不推断特殊疾病或延长。')
            submit()
            check(f'{region} opening special section and ordinary remarks leave balance unchanged',page.locator('.mp-balance strong').inner_text()==balance)
            text=receipt()
            check(f'{region} receipt records unchecked status and original note','特殊情况：未勾选' in text and '备注：普通备注：资料复核，不推断特殊疾病或延长。' in text)
            page.get_by_role('button',name='修改条件',exact=True).click()
            page.locator('[name="specialCircumstances"]').check()
            submit()
            check(f'{region} checked special case preserves records and blocks balance','特殊情况' in page.locator('.mp-balance').inner_text() and '待核对' == page.locator('.mp-balance strong').inner_text())
            check(f'{region} copy agrees with explicit special case','特殊情况：已勾选，待人工核对' in receipt())
            page.get_by_role('button',name='修改条件',exact=True).click()
            page.locator('[name="specialCircumstances"]').uncheck()
            submit()
            check(f'{region} unchecking restores balance while keeping notes',page.locator('.mp-balance strong').inner_text()==balance and '备注：普通备注' in receipt())
        reset(page)
        national(page)
        fill(page,'hireDate','2021-01-01')
        fill(page,'totalWorkYears','8')
        fill(page,'segments.0.startDate','2025-12-20')
        fill(page,'segments.0.endDate','2026-01-10')
        check('unit tenure tier crossing does not promote total-tenure date',page.locator('.mp-basic-fields [name="tenYearDate"]').count()==0)
        submit()
        check('unit tier crossing does not ask for irrelevant ten-year date','工龄跨档' in page.locator('.mp-balance').inner_text() and '满10年日期' not in page.locator('.mp-balance').inner_text())
        reset(page)
        national(page)
        fill(page,'hireDate','2022-01-01')
        fill(page,'totalWorkYears','8')
        fill(page,'segments.0.startDate','2023-04-04')
        fill(page,'segments.0.endDate','2023-04-08')
        page.get_by_role('button',name='非连续分段',exact=True).click()
        page.get_by_role('button',name='添加一段病休',exact=True).click()
        fill(page,'segments.1.startDate','2024-06-06')
        fill(page,'segments.1.endDate','2024-06-13')
        check('multi-year ambiguous tenure promotes date',page.locator('.mp-basic-fields [name="tenYearDate"]').is_visible())
        submit()
        check('multi-year uncertainty retains known segment result and stops ambiguous balance','86天（参考）' in page.locator('.mp-segment-result').nth(0).inner_text() and '满10年日期' in page.locator('.mp-segment-result').nth(1).inner_text())
        reset(page)
        shanghai(page)
        page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied')}}})")
        submit()
        page.get_by_role('button',name='复制测算单',exact=True).click()
        expect(page.locator('#mp-copy-text')).to_be_visible()
        check('clipboard failure offers matching read-only receipt','54.01工作日' in page.locator('#mp-copy-text').input_value() and page.locator('#mp-copy-text').get_attribute('readonly') is not None)
        page.get_by_role('button',name='修改条件',exact=True).click()
        fill(page,'segments.0.workDays','7')
        check('editing removes stale manual copy',page.locator('#mp-copy-text').count()==0)
        page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise(resolve=>{window.__copyResolve=resolve})}})")
        submit()
        page.get_by_role('button',name='复制测算单',exact=True).click()
        page.get_by_role('button',name='修改条件',exact=True).click()
        fill(page,'segments.0.workDays','6')
        page.evaluate('window.__copyResolve()')
        check('late clipboard completion cannot show fresh success',page.locator('.mp-notice').count()==0)
        untouched('all edits,resets,calculations,copies leave history untouched')
        page.reload(wait_until='networkidle')
        check('refresh starts empty form',page.locator('[name="region"]').input_value()=='' and page.locator('.mp-result').count()==0)
        untouched('reload ignores old snapshots without overwriting them')
        blocked_context=browser.new_context()
        blocked_context.add_init_script("for(const name of ['getItem','setItem','removeItem'])Storage.prototype[name]=()=>{throw new Error('Storage unavailable')}")
        blocked=blocked_context.new_page()
        blocked.goto(url,wait_until='networkidle')
        shanghai(blocked)
        blocked.get_by_role('button',name='开始测算',exact=True).click()
        expect(blocked.locator('.mp-balance')).to_contain_text('54.01')
        check('calculation works with browser storage unavailable')
        blocked_context.close()
        check('no API or model calls',not api_requests)
        check('no external resources',not external_requests)
        check('no HTTP failures',not http_failures)
        check('no browser errors: '+json.dumps(errors,ensure_ascii=False),not errors)
        browser.close()
    hashes={name:hashlib.sha256((review_root/name).read_bytes()).hexdigest() for name in ['src/pages/MedicalCalculatorPage.jsx','src/pages/MedicalCalculatorPage.css','src/utils/medical-period-calculator.js']}
    report={'status':'passed','checks':len(checks),'cases':checks,'pageErrors':errors,'apiRequests':api_requests,'externalRequests':external_requests,'httpFailures':http_failures,'sourceFilesSHA256':hashes,'scope':'isolated actual medical page; fictional data; not business acceptance or deployment'}
    (output/'verification.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
    print(json.dumps({'status':'passed','checks':len(checks),'output':str(output)},ensure_ascii=False))
finally:
    server.terminate()
    server.wait(timeout=20)
